spring:
  application:
    name: joj-backend-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # 暂时禁用服务注册
        # register-enabled: false
    gateway:
      routes:
        - id: joj-backend-user-service
          uri: lb://joj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: joj-backend-question-service
          uri: lb://joj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: joj-backend-judge-service
          uri: lb://joj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  main:
    web-application-type: reactive

server:
  address: 0.0.0.0
  port: 8101

knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
