version: '3'
services:
  # -------------------------------
  # MySQL
  # -------------------------------
  mysql:
    image: mysql:8 # 使用的镜像
    container_name: joj-mysql # 启动的实例名称
    environment:
      MYSQL_ROOT_PASSWORD: 666666 # root 用户密码
      TZ: Asia/Shanghai
    ports:
      - "3306:3306" # 端口映射
    volumes:
      - ./.mysql-data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
      - ./mysql-init:/docker-entrypoint-initdb.d # 启动脚本
    restart: always # 崩溃后自动重启
    networks:
      - JojNetwork # 指定网络

  # -------------------------------
  # Redis
  # -------------------------------
  redis:
    image: redis:6
    container_name: joj-redis
    command: redis-server --requirepass "666666"
    ports:
      - "6379:6379"
    networks:
      - JojNetwork
    volumes:
      - ./.redis-data:/data # 持久化
    restart: always

  # -------------------------------
  # RabbitMQ
  # -------------------------------
  rabbitmq:
    image: rabbitmq:3.12.6-management # 支持管理面板的消息队列
    container_name: joj-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Dashboard 端口
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq # 持久化
    networks:
      - JojNetwork
    restart: always

  # -------------------------------
  # Nacos
  # -------------------------------
  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: joj-nacos
    ports:
      - "8848:8848"
      - "9848:9848" # gRPC 客户端请求端口 (用于服务注册与发现)
      # Nacos 2.2.0 之后的版本，9849 已被弃用，但为保险起见可以加上
      - "9849:9849" # gRPC 客户端请求端口（旧版）
    volumes:
      - ./.nacos-data:/home/nacos/data
      - ./.nacos-logs:/home/nacos/logs
    networks:
      - JojNetwork
    environment:
      - MODE=standalone # 单节点模式启动
      - PREFER_HOST_MODE=hostname # 支持 hostname
      - TZ=Asia/Shanghai # 控制时区
    restart: always

networks:
  JojNetwork: